import {useState} from 'react';
import {Boxes,LayoutDashboard,Package,ClipboardList,Calculator,FolderOpen,Palette,Settings,Plus,Search} from 'lucide-react';
import {Badge,Button,Card,Field,PageHeader} from './components/ui';
const nav=[['Dashboard',LayoutDashboard],['Inventory',Boxes],['Products',Package],['Orders & Production',ClipboardList],['Pricing',Calculator],['Files & Assets',FolderOpen],['Brand & Design',Palette],['Admin',Settings]];
function DesignSystem(){return <><PageHeader eyebrow="Admin · Development Design" title="Design System" description="The live component library for Simply Ummiby Workshop. We can change the personality later without rebuilding screens."/>
<Card><h2>Buttons</h2><div className="row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button disabled>Disabled</Button></div></Card>
<Card><h2>Forms</h2><div className="form-grid"><Field label="Material name" placeholder="Natural macramé cord"/><Field label="Quantity" type="number" placeholder="100"/><Field label="Cost" type="number" placeholder="8.99"/></div></Card>
<Card><h2>Cards & status</h2><div className="sample-grid"><Card className="nested"><div className="eyebrow">CORD</div><h3>Natural Macramé Cord</h3><p>3 mm · 100 yd</p><Badge tone="warning">Low stock</Badge></Card><Card className="nested"><div className="eyebrow">PRODUCT</div><h3>Classic TP Holder</h3><p>Natural · Base product</p><Badge>Draft</Badge></Card></div></Card></>}
function Inventory(){return <><PageHeader eyebrow="Workshop" title="Inventory" description="Supplies, materials, quantities, costs, and where everything lives." action={<Button><Plus size={16}/> Add material</Button>}/><div className="toolbar"><div className="search"><Search size={17}/><input aria-label="Search inventory" placeholder="Search materials…"/></div><Button variant="secondary">Filters</Button></div><Card className="empty"><Boxes size={34}/><h2>Your inventory starts here</h2><p>Add the real supplies you use. Products and pricing will later consume these inventory records.</p><Button><Plus size={16}/> Add first material</Button></Card></>}
function Placeholder({name}){return <><PageHeader eyebrow="Company Hub" title={name} description="This area is part of the permanent v2 architecture and will connect to the same shared data model."/><Card className="empty"><h2>{name} foundation reserved</h2><p>We’ll activate this module as its connected workflow is built.</p></Card></>}
export default function App(){const [active,setActive]=useState('Inventory');return <div className="app"><aside><div className="brand"><div className="mark">SU</div><div><strong>Simply Ummiby</strong><span>Company Hub</span></div></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><I size={18}/>{n}</button>)}</nav><div className="admin-link"><button className={active==='Design System'?'active':''} onClick={()=>setActive('Design System')}><Palette size={18}/>Design System</button></div></aside><main>{active==='Inventory'?<Inventory/>:active==='Design System'?<DesignSystem/>:<Placeholder name={active}/>}</main></div>}